name: hackathon_env
channels:
  - defaults
dependencies:
  - python>3.8
  - pip:
    - requests==2.31.0
    - connexion==3.0.0
    - connexion[flask]
    - connexion[swagger-ui]
    - connexion[uvicorn]
    - a2wsgi==1.10.6
    - fastapi==0.111.0
    - pyjwt==2.8.0
    - six==1.16.0
